name: "Build"

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install System Dependencies
        run: |
          sudo apt-get update -qq \
          && sudo apt-get install --no-install-recommends -y \
              build-essential \
              gcc \
              cmake \
              make \
              pkg-config \
              wget \
              libcairo2-dev \
              libffi-dev \
              libpango1.0-dev \
              libegl-dev \
          && sudo rm -rf /var/lib/apt/lists/* # Fixed: added 'sudo' to all commands
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Python 3.11
        run: uv python install 3.11
      - name: Build
        run: uv build
